= Rest OAth2 Ant
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

toc::[]

== TO-DO

- Exception customizado capaz de retornar httStatusCode e errorCode
- helper/get-table-info precisa criar cache das tabelas já pesquisadas
- implementar OAuth2
- implementar o método HTTP options
- permitir outros tipos de retorno além do JSON (XML)

== Fluxo das Requisições e respostas

....
                                   ┌─────────────┐                         ┌──────────────┐
   ┌─────────┐                     │ SERVIDOR DE │                         │ SERVIDOR DE  │
   │ CLIENTE │                     │  APLICAÇÃO  │                         │ AUTENTICAÇÃO │
   └────┬────┘                     └─────┬───────┘                         └─────┬────────┘
        │                                │                                       │	
        │                                │                                       │	
        ├───┤ Authorization Grant ├──────┼──────────────────────────────────────>│	
        │                                │                                       │	
        │                                │                                       │	
        │<───────────────────────────────┼────┤ Access Token & Refresh Token ├───┤	
        │                                │                                       │	
        │                                │                                       │	
        ├───┤ HTTP REQUEST + TOKEN ├────>│                                       │	
        │                                │                                       │	
        │                                │                                       │ 
        │                                │     ┌───────────────────────────┐     │	
        │                                ├────>│ loadConfig()              │     │	
        │                                │     │ parse()                   │     │	
        │                                │     │ ↳ parseMethod()           │     │
        │                                │     │ ↳ parseAction()           │     │	
        │                                │     │ ↳ parseQuery()            │     │	
        │                                │     │ ↳ parseBody()             │     │	
        │                                │     │ handlerHelperValidators() │     │	
        │                                │     │ pdo()                     │     │	
        │                                │     │ loadAction()              │     │	
        │                                │     │ check()                   │     │	
        │                                │     │ ↳ checkQuery()            │     │	
        │                                │     │ ↳ checkBody()             │     │	
        │                                │     │ executeCallback()         │     │	
        │                                │<────┤ trata o retorno()         │     │	
        │                                │     └───────────────────────────┘     │	
        │                                │                                       │	
        │                                │                                       │	
        │<────────────┤ HTTP RESPONSE ├──┤                                       │	
        │                                │                                       │	
        │                                │                                       │	
 
....

- 1. O cliente faz uma requisição HTTP para a aplicação seguindo o seguinte padrão:
    * A URL de acesso deve seguir o seguinte padrão http(s)://dominio_da_aplicaçao/nome_do_action/...path?query_string
        ** nome_do_action (..)
        ** ...path (..)
        ** query_string deve seguir o seguinte padrão ?chave1=valor1&chave2=valor2&chaveN=valorN
    * Informar o METHOD como get, put, post ou delete.
    * O corpo da requisição deve conter um JSON válido.
- 2. A aplicação recebe a requisição HTTP e faz os sguintes processos:
    * 01 loadConfig()                      : carrega o arquivo de configuração
    * 02 parseMethod()                     : higieniza o nome do método com o qual a aplicação foi requisitada (get, put, post, delete).
    * 03 parseAction()                     : transforma o valores da URL (nome_do_action/...path), em um array no seguinte padrão: `[ "path" => nome_do_action, path => ...path ]`
    * 04 parseQuery()                      : transforma a `query_string` em um array
    * 05 parseData()                       : transforma o corpo da reuisição em um array
    * 06 handlerHelperValidators()         : 
    * 07 pdo()                             : conecta-se ao banco de dados
    * 08 loadAction()                      : carrega o arquivo de action conforme a chave `name` gerada no passo `03` e nome do método da requisição HTTP higienizado no passo `02`
    * 09 checkQuery()                      : checa e formata os valores carregados no passo `02` com as informações contidas no arquivo `action` carregado pelo passo `08`
    * 10 checkData()                       : checa e formata os valores carregados no passo `03` com as informações contidas no arquivo `action` carregado pelo passo `08`
    * 11 executeCallback()                 : executa o callback 
    * 12 `try` go() `catch` trata resposta : trata os erros e responde a requisição HTTP o resultado obtido no passo `11` de volta ao cliente

(..)

== Configurações

As configurações são feitas no arquivo `config.php` (..)

== Rest

...

=== O que são Actions 

São arquivos que determinam as ações que a aplicação executará conforme o método de acesso da `requisição HTTP`, além de tratar as entradas de informações enviadas pela `query-string` e `body-content` da `requisição HTTP`.

(..)

A variavel `$this` dentro de uma funcão `callback` tem o contexto `HandlerHelpersValidators`

=== O que são Helpers 

São arquivos que retornam funções que podem facilitar tarefas comuns da apicação (..)

A variavel `$this` dentro de uma funcão `helper` tem o contexto `HandlerHelpersValidators` e pode ser acessada em qualquer outro contexo, utilizando a seguinte sintaxe:

[source,php]
....
$this->helper(nome_do_helper)(... parametros);
....

Helpers por padrão são armazenados na pasta `./helpers`, porém é possível configurar este local no arquivo `config.php`, através da entrada `folder -> helper`.

(..)

=== O que são Validators

São arquivos que retornam funções que podem validam dados, estes arquivos são executados no momento em que as informações oriundas `query-string` e `body-content` da `requisição HTTP` são verificadas (..), 

A variavel `$this` dentro de uma funcão `validator` tem o contexto `HandlerHelpersValidators`.

(..)

Validators por padrão são armazenados na pasta `./validators`, porém é possível configurar este local no arquivo `config.php`, através da entrada `folder -> validator`.

=== O que são Automators

(..), 

A variavel `$this` dentro de uma funcão `automator` tem o contexto `????`

Automators por padrão são armazenados na pasta `./automators`, porém é possível configurar este local no arquivo `config.php`, através da entrada `folder -> automator`.

=== Contextos

...

==== HandlerHelpersValidatos

...

==== HandlerActions

...

== OAuth2

...